# Generated by Django 3.2.4 on 2021-08-09 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0003_auto_20210728_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tlspolicy',
            name='policy',
            field=models.CharField(choices=[('SM', 'Simulate'), ('PX', 'Proxy'), ('IV', 'INVALID')], default='SM', max_length=2),
        ),
        migrations.CreateModel(
            name='HTTPPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dst_ip', models.GenericIPAddressField()),
                ('dst_port', models.IntegerField()),
                ('counter', models.IntegerField()),
                ('policy', models.CharField(choices=[('SM', 'Simulate'), ('PX', 'Proxy'), ('IV', 'INVALID')], default='SM', max_length=2)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list.analysis')),
            ],
        ),
    ]
