# Generated by Django 3.2.4 on 2021-08-10 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0005_uploadfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadfile',
            name='file',
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='file_path',
            field=models.TextField(default=''),
        ),
    ]
